### ISSUE TITLE
Spring Boot applications packaged using "package" and "docker-build" goal should not run on defaultHost by default.

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/boost#213] opened 2018-11-15 21:23 UTC
Right now the `package` and the `docker-build` goal packages the application into uber jar and docker image respectively. The uber jar and the docker image runs on defaultHost by default.

`package` case:  The `server.liberty.use-default-host` can be set to `false` in bootstrap.properties while packaging the uber jar. This would enable the application to use the Spring Boot properties set in the application.properties file.

`docker-build` case: Will have to think on this. Maybe we create a docker image of open-liberty having server.liberty.use-default-host=false` already set in bootstrap.properties

**Comment by scottkurz** [comment] 2018-11-15 22:08
@anjumfatima90 , thank you for noting this.   This has come up already though, in Gitter, where we have discussed it already but without making a decision.  

I'm sorry I don't have a single thread to point you to right now (except Gitter itself).

In the meantime, though, I wanted to save you from coding this while the discussion is pending.

**Comment by anjumfatima90** [comment] 2018-11-15 22:18
Sure. @scottkurz

**Comment by barecode** [comment] 2018-11-16 09:17
To be clear on the expected external behaviour, if I am using Spring Boot + Tomcat, and I want to switch to Spring Boot + Liberty, I should get the *same ports* my app is using on Tomcat. If I am taking the "spring defaults", which is host=* httpPort=8080 with Tomcat, then I should get the same behaviour in Liberty. Otherwise, if I do not have this expected behaviour, Liberty will look like its doing the 'wrong' thing, and the user's expectations are violated.

**Comment by scottkurz** [comment] 2018-11-16 15:44
OK, so let me see if I can be helpful here.   Notifying @awisniew90 to keep me honest.

On Gitter, etc., we've talked about honoring the `server.liberty.use-default-host=false` and delegating to SB to set the related properties, and have more discussion pending (e.g. from @NottyCode).

In the meantime, though, w/o a decision to make that change, we're reading a subset of SpringBoot props in a subset of ways (not in every way a SpringBoot user can set them).

In particular, I think we honor **server.port** and **server.address**.

So @barecode are you saying we are doing something wrong even when going with the defaultHttpEndpoint approach?    If so, what?   Or is this just another issue saying we should  honor `server.liberty.use-default-host=false`  instead?

**Comment by awisniew90** [comment] 2018-11-19 20:50
So in either case (defaultHttpEndpoint or server.liberty.use-default-host=false, we should be honoring the SB defaults (i.e. port 8080).  What we are lacking now with using the defaultHttpEndpoint is the ability to override properties at _runtime_. We also currently lack any way to set the properties via application.yml. I think the server.liberty.use-default-host=false is a better route to go as it gives us the greatest _functional_ compatibility with SB+Tomcat in regards to setting and overriding properties.

**Comment by awisniew90** [comment] 2018-11-20 19:55
The server.port and server.address are read from the application.properties file by the boost plugin. Those properties are copied over to the liberty server's bootstrap.properties file (providing default values if none were found in application.properties). At runtime ("java -jar myJar.jar"), those properties can be overridden using -D syntax, but that only works because bootstrap.properties allows for -D overrides. So this mirrors the non-boost spring boot -D override ability, but just that.  Any of the other override options that spring boot allows will not work.

**Comment by scottkurz** [comment] 2018-11-20 21:32
Hmm...I just tried adding `-Dserver.port=8081` to both `mvn boost:run` and `java -jar my.jar` and in neither case did it override what was packaged.   Do you have a sample?

**Comment by scottkurz** [comment] 2018-11-20 22:01
OK, I opened a separate issue https://github.com/OpenLiberty/boost/issues/215 since the override doesn't work for `mvn boost:run`.

**Comment by scottkurz** [comment] 2019-01-02 16:52
Resolved by #220

**Closed by scottkurz** 2019-01-02 16:52 UTC
